create table car
(
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    make varchar(255) not null,
    name varchar(255) not null,
    primary key(id)
);

create table dealer
(
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    name varchar(255) not null,
);

create table car_dealer(
    car_id integer not null,
    dealer_id integer not null,
    available_count integer not null,
    request_count integer not null,
    foreign key (car_id) references car(id),
    foreign key (dealer_id) references dealer(id),
    unique(car_Id, dealer_Id)
);